# Generated by Django 2.2.10 on 2020-03-28 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('nick_name', models.CharField(blank=True, max_length=120)),
                ('address_name', models.CharField(max_length=120)),
                ('address_type', models.CharField(choices=[('HOME', 'Deliver to Home'), ('OFFICE', 'Deliver to Office'), ('OTHER', 'Deliver to StoreHouse, etc')], max_length=120)),
                ('line1', models.CharField(max_length=120)),
                ('line2', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(default='India', max_length=50)),
                ('postal_code', models.CharField(max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
