# Generated by Django 2.2.10 on 2020-03-30 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addresses', '0001_initial'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking', models.CharField(choices=[('processing', 'processing'), ('in-transit', 'in-transit'), ('delivered', 'delivered'), ('returning', 'returning'), ('returned', 'returned')], max_length=120)),
                ('status', models.CharField(choices=[('delivered', 'delivered'), ('returned', 'returned'), ('refunded', 'refunded')], max_length=120)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='addresses.Address')),
                ('product_entries', models.ManyToManyField(to='carts.ProductEntry')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
