# Generated by Django 2.2.10 on 2020-02-22 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator('\\d{1, 2}', message='The discount should be lower than 100')]),
        ),
    ]
