# Generated by Django 2.2.10 on 2020-02-22 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200222_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator('(\\d){1, 2}', message='The discount should be lower than 100')]),
        ),
    ]
